CREATE TABLE Cohort (
Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
CohortName TEXT NOT NULL
);

CREATE TABLE Student (
Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
FirstName TEXT NOT NULL,
LastName TEXT NOT NULL,
SlackHandle TEXT NOT NULL,
StudentCohortId INTEGER NOT NULL,
FOREIGN KEY (StudentCohortId) REFERENCES Cohort(Id)
);

CREATE TABLE Instructor (
Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
FirstName TEXT NOT NULL,
LastName TEXT NOT NULL,
SlackHandle TEXT NOT NULL,
InstructorCohortId INTEGER NOT NULL,
FOREIGN KEY (CohortId) REFERENCES Cohort(Id)
);

CREATE TABLE Exercise (
Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
ExerciseName TEXT NOT NULL,
ExerciseLanguage TEXT NOT NULL,
);

INSERT INTO Cohort (Cohort26) VALUES ("Cohort 26");
INSERT INTO Cohort (Cohort27) VALUES ("Cohort 27");
INSERT INTO Cohort (Cohort28) VALUES ("Cohort 28");

INSERT INTO Student (Daniel) VALUES()